using System;
using System.Collections;
using System.Collections.Generic;
using System.Net;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;
using NpgsqlTypes;
using PlDotNET.Handler;
// $user_namespace$

/// <summary>
/// This namespace contains the classes dynamically created by PL.NET.
/// </summary>
namespace PlDotNET.UserSpace
{
    /// <summary>
    /// It does the `C->C#` and `C#->C` conversions and calls the user function.\n
    /// Example of UserHandler class generated by PL.NET for the following SQL function:
    /// ```
    /// CREATE OR REPLACE FUNCTION modifyInputDate(orig_date DATE) RETURNS DATE AS $$
    /// int day = orig_date.Day;
    /// int month = orig_date.Month;
    /// int year = orig_date.Year;
    /// DateOnly new_date = new DateOnly(year + 3, month + 1, day + 6);
    /// return new_date;
    /// $$ LANGUAGE plcsharp STRICT;
    /// ```
    /// </summary>
    public static class UserHandler
    {
        /// <summary>
        /// It does the `C->C#` and `C#->C` conversions and calls the user function.\n
        /// </summary>
        public static DateHandler DateHandlerObj = new DateHandler();

        /// <summary>
        /// C function declared in pldotnet_common.h to set the datum result.
        /// See ::pldotnet_SetDatumResult().
        /// </summary>
        [DllImport("/usr/lib/postgresql/14/lib/pldotnet.so")]
        public static extern void pldotnet_SetDatumResult(IntPtr value, [MarshalAs(UnmanagedType.I1)] bool isNull, IntPtr nativeResult);

        /// <summary>
        /// C function declared in pldotnet_conversions.h to return a void datum.
        /// See ::pldotnet_CreateDatumVoid().
        /// </summary>
        [DllImport("/usr/lib/postgresql/14/lib/pldotnet.so")]
        public static extern IntPtr pldotnet_CreateDatumVoid();

        /// <summary>
        /// The generated CallUserFunction for the SQL function.
        /// It does the necessary conversions and calls the user function.
        /// </summary>
        public static unsafe void CallUserFunction(List<IntPtr> arguments, IntPtr output, bool[] isnull)
        {
            // As the SQL function named modifyinputdate is `STRICT` or `RETURNS NULL ON NULL INPUT`,
            // `PL.NET` doesn't check whether any argument datum is null.
            // You can also set true for the `Engine.AlwaysNullable` variable
            // to always check whether the datum is null.

            // BEGIN create arguments for modifyinputdate
            var argument_0 = DateHandlerObj.InputValue(arguments[0]);
            // END create arguments for modifyinputdate
            var result = UserFunction.modifyinputdate((DateOnly)argument_0);
            var resultDatum = DateHandlerObj.OutputNullableValue(result);
            pldotnet_SetDatumResult(resultDatum, result == null, output);
        }
    }
}
