using System;
using System.Buffers;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Unicode;
using NpgsqlTypes;
using PlDotNET.Handler;

/// <summary>
/// This namespace contains the classes dynamically created by PL.NET.
/// </summary>
namespace PlDotNET.UserSpace
{
    /// <summary>
    /// Stores the user function. It's generated and compiled by PL.NET.\n
    /// Example of UserFunction class generated by PL.NET for the following SQL function:
    /// ```
    /// CREATE OR REPLACE FUNCTION modifyInputDate(orig_date DATE) RETURNS DATE AS $$
    /// int day = orig_date.Day;
    /// int month = orig_date.Month;
    /// int year = orig_date.Year;
    /// DateOnly new_date = new DateOnly(year + 3, month + 1, day + 6);
    /// return new_date;
    /// $$ LANGUAGE plcsharp STRICT;
    /// ```
    /// </summary>
    public static class UserFunction
    {
        /// <summary>
        /// The C# function created from the SQL function.
        /// </summary>
        public static DateOnly? modifyinputdate(DateOnly orig_date)
        {
#line 1
            int day = orig_date.Day;
            int month = orig_date.Month;
            int year = orig_date.Year;
            DateOnly new_date = new DateOnly(year + 3, month + 1, day + 6);
            return new_date;
        }
    }
}
