FROM postgres:10-stretch

# avoids tzdata prompt
ARG DEBIAN_FRONTEND=noninteractive

# Requirements
RUN apt-get update \
    && apt install -y \
        wget \
        devscripts \
        debhelper \
        pkg-config \
        apt-transport-https \
        curl \
        libglib2.0-dev \
        software-properties-common

# .NET Core
RUN wget -q \
        https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb \
        -O packages-microsoft-prod.deb \
    && dpkg -i \
        packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y \
        dotnet-sdk-3.1

# POSTGRESQL
RUN apt install -y \
        postgresql-server-dev-10

# PLDOTNET
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

RUN runuser -u postgres -- \
        initdb \
    && runuser -u postgres -- \
        pg_ctl start \
    && runuser -u postgres -- \
        psql -c  \
        "DO \$\$ BEGIN CREATE ROLE root superuser createdb login createrole replication bypassrls; EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE; END \$\$;" \
    && make clean \
    && make \
    && make plnet-install

ENTRYPOINT [ "bash", "/app/pldotnet/Dockerfiles/scripts/start_pg.sh" ]
