FROM ubuntu:21.04

# avoids tzdata prompt
ARG DEBIAN_FRONTEND=noninteractive

# Requirements
RUN apt-get update \
    && apt install -y \
        wget \
        devscripts \
        debhelper \
        pkg-config \
        apt-transport-https \
        libglib2.0-dev

# .NET Core
RUN wget -q \
        https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb \
        -O packages-microsoft-prod.deb \
    && dpkg -i \
        packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y \
        dotnet-runtime-3.1 \
        dotnet-sdk-3.1 \
        dotnet-hostfxr-3.1

# POSTGRESQL
RUN apt install -y \
        postgresql \
        postgresql-common \
        postgresql-server-dev-all

# PLDOTNET
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

RUN service postgresql start \
    && runuser \
        -u postgres -- \
        psql -c \
        "DO \$\$ BEGIN CREATE ROLE root superuser createdb login createrole replication bypassrls; EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE; END \$\$;" \
    && make clean \
    && make \
    && make plnet-install \
    && service postgresql stop

ENTRYPOINT [ "bash", "/app/pldotnet/Dockerfiles/scripts/start_pg.sh" ]
