FROM postgres:10-stretch

# avoids tzdata prompt
ARG DEBIAN_FRONTEND=noninteractive

# Requirements
RUN apt-get update \
    && apt install -y \
        wget \
        libglib2.0-dev \
        apt-transport-https

# .NET Core
RUN wget -q \
        https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb \
        -O packages-microsoft-prod.deb \
    && dpkg -i \
        packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y \
        dotnet-sdk-3.1

# POSTGRESQL AND BUILD TOOLS
RUN apt update \
    && apt install -y \
        postgresql-server-dev-10 \
        lsb-release \
        build-essential

# PLDOTNET
# cluster creation requirements; locale settings
RUN apt update \
    && apt install -y \
        locales \
        rsync \
    && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# pgdata
ARG PGDATA
ENV PGDATA=${PGDATA}

# app files
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

# creating persistent cluster and installing extension
RUN bash /app/pldotnet/Dockerfiles/scripts/create_pg_cluster.sh \
    && bash /app/pldotnet/Dockerfiles/scripts/start_pg_cluster.sh \
    && bash /app/pldotnet/Dockerfiles/scripts/install_make.sh \
    && service postgresql stop \
    && rsync -a \
        ${PGDATA}/* /var/lib/postgresql/pgnet_backup_cluster

ENTRYPOINT [ "bash", "/app/pldotnet/Dockerfiles/scripts/start_pg_cluster.sh" ]
