stages:
  - prepare
  - build
  - test
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: true
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  POSTGRES_PORT: 5432
  DOTNET_VERSION: 9.0
  DATABASE_CONNECTION_STRING: "Host=127.0.0.1;Port=$POSTGRES_PORT;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD;Database=$POSTGRES_DB"
  TargetFramework: net9.0

.default-test-template: &test-template
  stage: test
  image: ubuntu:25.04
  interruptible: true
  before_script:
    - echo "$POSTGRES_VERSION" > debian/pgversions
    - apt update && apt upgrade -y
    - apt install -y make sudo curl wget gnupg
    - apt install -y postgresql-common
    - /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
    - apt install -y postgresql-$POSTGRES_VERSION
    - pg_ctlcluster $POSTGRES_VERSION main start
    - apt install -y libglib2.0-dev devscripts build-essential lintian debhelper postgresql-server-dev-all dotnet-sdk-$DOTNET_VERSION dotnet-runtime-$DOTNET_VERSION pkg-config
    - mkdir -p /app
    - ln -s "$CI_PROJECT_DIR" /app/pldotnet
  script:
    - make build-local
    - dpkg -i debian/packages/dotnet-$DOTNET_VERSION-postgresql-$POSTGRES_VERSION-pldotnet_0.99-rc1_amd64.deb
    - runuser -u $POSTGRES_USER -- psql -c "CREATE EXTENSION pldotnet; ALTER USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';"
    - make test-local

# Runs only on develop branch with full version matrix
test_matrix_develop:
  <<: *test-template
  parallel:
    matrix:
      - POSTGRES_VERSION: ["11", "12", "13", "14", "15", "16", "17"]
  resource_group: test-matrix-develop
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "push"'

# Runs on all merge requests for PG 17
test_pg17_merge_request:
  <<: *test-template
  variables:
    POSTGRES_VERSION: "17"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

generate-changelogs:
  stage: prepare
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*/
  script:
    - apk add curl jq
    - CI_COMMIT_TAG_NO_V=${CI_COMMIT_TAG#v}
    - echo "Fetching changelogs from $CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG_NO_V"
    - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG_NO_V" | jq -r .notes > release_notes.md'
  artifacts:
    paths:
      - release_notes.md
    expire_in: 1 week

build-deb:
  stage: build
  image: ubuntu:25.04
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*/'
  variables:
    POSTGRES_VERSION: "17"
  # before_script:
  #   - apt update && apt upgrade -y
  #   - apt install -y make sudo curl wget gnupg
  #   - apt install -y postgresql-common
  #   - /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
  #   - apt install -y postgresql-17
  #   - apt install -y libglib2.0-dev devscripts build-essential lintian debhelper postgresql-server-dev-all dotnet-sdk-$DOTNET_VERSION dotnet-runtime-$DOTNET_VERSION pkg-config
  script:
    # - make build-local
    - mkdir -p debian/packages
    - echo "Test" > debian/packages/dotnet-9.0-test.deb
  artifacts:
    paths:
      - debian/packages/dotnet-*
    expire_in: 1 week

create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: generate-changelogs
      artifacts: true
    - job: build-deb
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*/
  script:
    - apk add curl jq
    - |
      echo "Uploading release assets"
      mkdir -p dist
      cp debian/packages/dotnet-* dist/
      release_cli_args=""
      for file in dist/*; do
        echo "Uploading $file"
        filename=$(basename "$file")
        url="https://git.brickabode.com/DotNetInPostgreSQL/pldotnet/-/jobs/${CI_JOB_ID}/artifacts/raw/${file}?inline=false"
        asset_json="{ 'name': '${filename}', 'url': '${url}' }"
        release_cli_args="$release_cli_args --assets-link \"$asset_json\""
      done
      release-cli create \
        --name "$CI_COMMIT_TAG" \
        --tag-name "$CI_COMMIT_TAG" \
        --ref "$CI_COMMIT_SHA" \
        --description ./release_notes.md \
        $release_cli_args
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week
