stages:
  - test

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  POSTGRES_PORT: 5432
  DOTNET_VERSION: 9.0

test_matrix:
  stage: test
  image: ubuntu:25.04
  parallel:
    matrix:
      - POSTGRES_VERSION: ["11", "12", "13", "14", "15", "16", "17"]
  variables:
    PGHOST: postgres
    DBUSER: postgres
    DATABASE_CONNECTION_STRING: "Host=127.0.0.1;Port=5432;Username=postgres;Password=postgres;Database=postgres"
  interruptible: true
  resource_group: "test-matrix-$CI_COMMIT_REF_SLUG"
  before_script:
    - apt update
    - apt install -y make sudo curl wget gnupg
    - apt install -y postgresql-common
    - /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
    - apt install -y postgresql-$POSTGRES_VERSION
    - pg_ctl start
    - pg_ctlcluster $POSTGRES_VERSION main start
    - apt install -y libglib2.0-dev devscripts build-essential lintian debhelper postgresql-server-dev-all dotnet-sdk-$DOTNET_VERSION dotnet-runtime-$DOTNET_VERSION pkg-config
    - mkdir -p /app
    - ln -s "$CI_PROJECT_DIR" /app/pldotnet
    - echo "Waiting for PostgreSQL..."
    - |
      for i in {1..30}; do
        if pg_isready -p $POSTGRES_PORT -U $POSTGRES_USER; then
          echo "✅ PostgreSQL ready"
          break
        fi
        echo "⏳ Waiting ($i)..."
        sleep 2
      done

  script:
    - echo "$POSTGRES_VERSION" > debian/pgversions
    - make build-local
    - dpkg -i debian/packages/dotnet-$DOTNET_VERSION-postgresql-$POSTGRES_VERSION-pldotnet_0.99-rc1_amd64.deb
    - runuser -u postgres -- psql -c 'CREATE EXTENSION pldotnet;'
    - runuser -u postgres -- psql -c "ALTER USER postgres WITH PASSWORD '$POSTGRES_PASSWORD';"
    - make test-local
