version: '3.4'

x-interactive: &interactive
  tty: true        # docker run -t
  stdin_open: true # docker run -i

x-command: &command
  # command: sh -c "make installcheck"
  command: sh -c "bash"

x-pgdata: &pgdata
  PGDATA: /var/lib/postgresql/data

x-build-args: &build-args
  context: .
  args:
    <<: *pgdata

x-environment: &environment
  environment:
    USE_DOTNETBUILD: "FALSE"
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    <<: *pgdata

x-ports: &ports
  ports:
    - "5432:5432"

networks:
  db_network:
    name: pldotnet_network

services:
  pldotnet-ubuntu22: &pldotnet-current-container
    container_name: pldotnet-ubuntu22
    image: pldotnet:ubuntu22
    <<: *interactive
    <<: *command
    build:
      dockerfile: Dockerfiles/default/Dockerfile_ubuntu22
      <<: *build-args
    <<: *environment
    <<: *ports
    networks:
      db_network:
    volumes:
      - ./:/app/pldotnet/
      - ./postgres-data/ubuntu22:/var/lib/postgresql/data
