version: '3.4'

x-interactive: &interactive
  tty: true        # docker run -t
  stdin_open: true # docker run -i

x-command: &command
  # command: sh -c "make installcheck"
  command: sh -c "bash"

x-build-args: &build-args
  context: .
  args:
    DOTNET_VERSION: 3.1

x-ubuntu-environment: &ubuntu-environment
  environment:
    USE_DOTNETBUILD: "FALSE"

x-volumes: &volumes
  volumes:
    - $PWD/:/app/pldotnet/


services:
  pldotnet-deb:
    container_name: pldotnet-deb
    image: pldotnet:deb
    <<: *interactive
    <<: *command
    build:
      dockerfile: Dockerfiles/default/Dockerfile_deb
      <<: *build-args
    environment:
      USE_DOTNETBUILD: "FALSE"
      PGUSER: postgres
    <<: *volumes

  pldotnet-ubuntu18:
    container_name: pldotnet-ubuntu18
    image: pldotnet:ubuntu18
    <<: *interactive
    <<: *command
    build:
      dockerfile: Dockerfiles/default/Dockerfile_ubuntu18
      <<: *build-args
    <<: *ubuntu-environment
    <<: *volumes

  pldotnet-ubuntu20: &pldotnet-current-container
    container_name: pldotnet-ubuntu20
    image: pldotnet:ubuntu20
    <<: *interactive
    <<: *command
    build:
      dockerfile: Dockerfiles/default/Dockerfile_ubuntu20
      <<: *build-args
    <<: *ubuntu-environment
    <<: *volumes

  pldotnet-ubuntu21:
    container_name: pldotnet-ubuntu21
    image: pldotnet:ubuntu21
    <<: *interactive
    <<: *command
    build:
      dockerfile: Dockerfiles/default/Dockerfile_ubuntu21
      <<: *build-args
    <<: *ubuntu-environment
    <<: *volumes

  pldotnet-devenv:
    <<: *pldotnet-current-container
    container_name: pldotnet-devenv
    image: pldotnet:devenv
