version: '3.4'

x-interactive: &interactive
  tty: true        # docker run -t
  stdin_open: true # docker run -i

x-install-command: &install-command
  command: sh -c "bash /app/pldotnet/Dockerfiles/scripts/start_pg_non_persistent.sh && bash /app/pldotnet/Dockerfiles/scripts/install_make.sh && bash /app/pldotnet/Dockerfiles/scripts/test_make.sh"

x-build-args: &build-args
  context: .
  args:
    DOTNET_VERSION: 3.1

x-ubuntu-environment: &ubuntu-environment
  environment:
    USE_DOTNETBUILD: "FALSE"

x-install-volumes: &volumes
  volumes:
    - $PWD/installation_test_results/plnet_install/:/app/pldotnet/installation_test_results/plnet_install/


services:
  pldotnet-deb:
    container_name: pldotnet-deb-make
    image: pldotnet:deb-make
    <<: *interactive
    <<: *install-command
    build:
      dockerfile: Dockerfiles/make_plnet_install/Dockerfile_deb-make
      <<: *build-args
    environment:
      USE_DOTNETBUILD: "FALSE"
      PGUSER: postgres
    <<: *volumes

  pldotnet-ubuntu18:
    container_name: pldotnet-ubuntu18-make
    image: pldotnet:ubuntu18-make
    <<: *interactive
    <<: *install-command
    build:
      dockerfile: Dockerfiles/make_plnet_install/Dockerfile_ubuntu18-make
      <<: *build-args
    <<: *ubuntu-environment
    <<: *volumes

  pldotnet-ubuntu20:
    container_name: pldotnet-ubuntu20-make
    image: pldotnet:ubuntu20-make
    <<: *interactive
    <<: *install-command
    build:
      dockerfile: Dockerfiles/make_plnet_install/Dockerfile_ubuntu20-make
      <<: *build-args
    <<: *ubuntu-environment
    <<: *volumes

  pldotnet-ubuntu21:
    container_name: pldotnet-ubuntu21-make
    image: pldotnet:ubuntu21-make
    <<: *interactive
    <<: *install-command
    build:
      dockerfile: Dockerfiles/make_plnet_install/Dockerfile_ubuntu21-make
      <<: *build-args
    <<: *ubuntu-environment
    <<: *volumes
