version: '3.4'

x-interactive: &interactive
  tty: true        # docker run -t
  stdin_open: true # docker run -i

x-install-command: &install-command
  command: sh -c "bash /app/pldotnet/Dockerfiles/scripts/install_package.sh && bash /app/pldotnet/Dockerfiles/scripts/test_package.sh"

x-build-args: &build-args
  context: .
  args:
    DOTNET_VERSION: 3.1

x-ubuntu-environment: &ubuntu-environment
  environment:
    USE_DOTNETBUILD: "FALSE"

x-install-volumes: &install-volumes
  volumes_from:
    - pldotnet-build:ro
  volumes:
    - $PWD/installation_test_results/deb/:/app/pldotnet/installation_test_results/deb/


services:
  pldotnet-build:
    container_name: pldotnet-build
    image: pldotnet:build
    <<: *interactive
    command: sh -c "bash /app/pldotnet/Dockerfiles/scripts/build_packages.sh"
    build:
      dockerfile: Dockerfiles/deb_package/Dockerfile_deb-build
      <<: *build-args
    environment:
      USE_DOTNETBUILD: "FALSE"
      PGDATA: /var/lib/postgresql/data1/
      POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_PASSWORD: # your password
    volumes:
      - $PWD/debian/packages:/app/pldotnet/debian/packages

  pldotnet-deb:
    container_name: pldotnet-deb-install
    image: pldotnet:deb-install
    <<: *interactive
    <<: *install-command
    build:
      dockerfile: Dockerfiles/deb_package/Dockerfile_deb-install
      <<: *build-args
    environment:
      USE_DOTNETBUILD: "FALSE"
      PGDATA: /var/lib/postgresql/data2/
      POSTGRES_HOST_AUTH_METHOD: trust
    <<: *install-volumes

  pldotnet-ubuntu18:
    container_name: pldotnet-ubuntu18-install
    image: pldotnet:ubuntu18-install
    <<: *interactive
    <<: *install-command
    build:
      dockerfile: Dockerfiles/deb_package/Dockerfile_ubuntu18-install
      <<: *build-args
    <<: *ubuntu-environment
    <<: *install-volumes

  pldotnet-ubuntu20:
    container_name: pldotnet-ubuntu20-install
    image: pldotnet:ubuntu20-install
    <<: *interactive
    <<: *install-command
    build:
      dockerfile: Dockerfiles/deb_package/Dockerfile_ubuntu20-install
      <<: *build-args
    <<: *ubuntu-environment
    <<: *install-volumes

  pldotnet-ubuntu21:
    container_name: pldotnet-ubuntu21-install
    image: pldotnet:ubuntu21-install
    <<: *interactive
    <<: *install-command
    build:
      dockerfile: Dockerfiles/deb_package/Dockerfile_ubuntu21-install
      <<: *build-args
    <<: *ubuntu-environment
    <<: *install-volumes
