<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="FSharpCompiler.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Compiler.Service" Version="41.0.5" />
  </ItemGroup>

  <Target Name="SetupForDemo"
    AfterTargets="Build">

    <ItemGroup>
      <AllOutputs Include="$(OutputPath)$(MSBuildProjectName).dll" />
      <AllOutputs Include="$(OutputPath)$(MSBuildProjectName).pdb" />
      <AllOutputs Include="$(OutputPath)$(MSBuildProjectName).runtimeconfig.json" />
      <AllOutputs Include="$(OutputPath)$(MSBuildProjectName).deps.json" />
      <AllOutputs Include="$(OutputPath)*.dll" />
    </ItemGroup>

    <!-- Copy the project outputs to the demo directory -->
    <Copy SourceFiles="@(AllOutputs)"
	    DestinationFolder="./" />
  </Target>

</Project>