FROM postgres:15.1-bullseye

# sets dotnet version, defaults to 6
ARG DOTNET_VERSION=6.0
ENV DOTNET_VERSION=${DOTNET_VERSION}
ENV TargetFramework=net${DOTNET_VERSION}

# PLDOTNET
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

# Do all the things
RUN apt update &&  apt install -y make
RUN make -f /app/pldotnet/docker/scripts/Makefile-builder deb_build

ENTRYPOINT [ "bash", "/app/pldotnet/docker/scripts/create_and_start_cluster.sh" ]
