#!/bin/bash
set -e

# Add nethost to ld.so search path.  We welcome more subtle solutions.
DOTNET_VERSION=$(dotnet --info | grep 'Host' -A 3 | grep Version:|awk '{print $2}')
DOTNET_LIBDIR=/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/${DOTNET_VERSION}/runtimes/linux-x64/native/
PLNET_ENGINE_DIR=/var/lib/DotNetEngine
PKG_LIBDIR=$(pg_config --pkglibdir | sed 's/\//\\\//g')
echo "${DOTNET_LIBDIR}" > /etc/ld.so.conf.d/nethost_pldotnet.conf
sed -i "s/@PKG_LIBDIR/${PKG_LIBDIR}/g" ${PLNET_ENGINE_DIR}/src/csharp/Engine.cs
sed -i "s/@PKG_LIBDIR/${PKG_LIBDIR}/g" ${PLNET_ENGINE_DIR}/src/csharp/TypeHandlers/*.cs
sed -i "s/@PKG_LIBDIR/${PKG_LIBDIR}/g" ${PLNET_ENGINE_DIR}/src/csharp/templates/csharp.tcs
CSHARP_TEMPLATE_DIR=/var/lib/DotNetEngine/src/csharp/templates
# sed -i "s/@CSHARP_TEMPLATE_DIR/${CSHARP_TEMPLATE_DIR}/g" ${PLNET_ENGINE_DIR}/src/csharp/Engine.cs
cat  /var/lib/DotNetEngine/src/csharp/Engine.cs | perl -ane "s#\@CSHARP_TEMPLATE_DIR#/var/lib/DotNetEngine/src/csharp/templates#g; print" > q && mv q /var/lib/DotNetEngine/src/csharp/Engine.cs
# # sed -i "s/@PKG_LIBDIR/${PKG_LIBDIR}/g" ${PLNET_ENGINE_DIR}/src/fsharp/FSharpEngine.fs
dotnet build ${PLNET_ENGINE_DIR}/src/csharp -c Release
# # dotnet build ${PLNET_ENGINE_DIR}/src/fsharp
ldconfig -v &> /dev/null # We need -v for ldconfig otherwise it won't work
runuser -u postgres -- psql -c "DROP EXTENSION IF EXISTS pldotnet CASCADE;"
runuser -u postgres -- psql -c "CREATE EXTENSION pldotnet;"
runuser -u postgres -- psql -c "DO \$\$ BEGIN CREATE ROLE root superuser createdb login createrole replication bypassrls; EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE; END \$\$;"

# FIXME: add a question to the user (debconf?  whatever the standard mechanism is) to ask them:
# FIXME: For a prompt, it's necessary to use debconf, apt-utils and dialog (or other frontend tool that follow debian specifications)
# runuser -u postgres -- psql -c "CREATE OR REPLACE FUNCTION pldotnet_Trust(boolean) RETURNS void AS \$\$ UPDATE pg_catalog.pg_language SET lanpltrusted = \$1 WHERE lanname='\'plcsharp\'' OR lanname='\'plfsharp\'' \$\$ LANGUAGE sql;"

# message="Warning: the PostgreSQL procedural languages from pldotnet,
# plcsharp and plfsharp, have not been audited for security.  We do
# not recommend installing them as trusted languages into sensitive
# environments.  However, if you are merely evaluating these languages,
# then installing them as trusted languages is much more convenient, as
# normal users can then use them without restriction.  We recommend only
# installing them as trusted languages in *untrusted* database environments.

# Would you like to install plcsharp and plfsharp as trusted languages?  (y/N)
# "

# echo -n "${message}"
# read like
# case "$like" in
# y*|Y*)
#    su - postgres -c 'psql -c "SELECT pldotnet_Trust(true);"'
# ;;
# n*|N*)
#     echo "You will need postgres/admin user execute 'SELECT pldotnet_Trust(true|false);' to turn plcsharp/plfsharp usable (trustable in your database);'"
# ;;
# esac
