FROM ubuntu:18.04

# avoids tzdata prompt
ARG DEBIAN_FRONTEND=noninteractive

# PLDOTNET
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

# Do all the things
RUN apt update &&  apt install make
RUN make -f /app/pldotnet/Dockerfiles/scripts/Makefile-builder ubuntu18_install