FROM postgres:10-stretch

# PLDOTNET
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

# Do all the things
RUN apt update &&  apt install make
RUN make -f /app/pldotnet/Dockerfiles/scripts/Makefile-builder deb_build

ENTRYPOINT []
