FROM postgres:10-stretch

# avoids tzdata prompt
ARG DEBIAN_FRONTEND=noninteractive

# Requirements
RUN apt-get update \
    && apt install -y \
        wget \
        libglib2.0-dev \
        apt-transport-https

# .NET Core
RUN wget -q \
        https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb \
        -O packages-microsoft-prod.deb \
    && dpkg -i \
        packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y \
        dotnet-sdk-3.1

# POSTGRESQL AND BUILD TOOLS
RUN apt update \
    && apt install -y \
        postgresql-server-dev-all \
        lsb-release \
        devscripts

# TEST ENV DIR
RUN mkdir -p /var/log/postgresql/data1

# PLDOTNET
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

ENTRYPOINT []
