FROM ubuntu:21.04

# PLDOTNET
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

RUN apt update &&  apt install make
RUN make -f /app/pldotnet/Dockerfiles/scripts/Makefile-builder ubuntu21_install

ENTRYPOINT []
