FROM postgres:10-stretch

# avoids tzdata prompt
ARG DEBIAN_FRONTEND=noninteractive

# Requirements
RUN apt-get update \
    && apt install -y \
        wget \
        devscripts \
        debhelper \
        pkg-config \
        apt-transport-https \
        curl \
        libglib2.0-dev \
        software-properties-common

# DEV
RUN apt update && \
    apt install -y \
        vim \
        tree \
        mlocate \
        tmux

# .NET Core
RUN wget -q \
        https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb \
        -O packages-microsoft-prod.deb \
    && dpkg -i \
        packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y \
        dotnet-sdk-3.1

# POSTGRESQL
RUN apt install -y \
        postgresql-server-dev-all

# PLDOTNET
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

ENTRYPOINT []
