FROM postgres:10-stretch

# TEST ENV DIR
RUN mkdir -p /var/log/postgresql/data2

# PLDOTNET
COPY . /app/pldotnet/
WORKDIR /app/pldotnet

RUN apt update &&  apt install make
RUN make -f /app/pldotnet/Dockerfiles/scripts/Makefile-builder deb_install

ENTRYPOINT []
