#+Title: Installation

* Requirements

+ [[https://www.postgresql.org/][PostgreSQL 9]] or greater
+ [[https://github.com/dotnet/core][.NET Core 3.1]]
+ [[https://www.docker.com/][Docker]] and [[https://docs.docker.com/compose/install/][Docker Compose]] (Optional and only for non Linux OSes)
Pldotnet also requires `libglib2.0` and `make`. If you want to test the installation you'll also need `lsb-release` installed.
You can install them with

#!+BEGIN_SRC
$ sudo apt-get update
$ sudo apt-get install -y libglib2.0-dev build-essential lsb-release
#!+END_SRC

* Installing .NET Core

For installing .NET Core please follow the instructions at the .NET Core
[[https://docs.microsoft.com/dotnet/core/install/linux-package-manager-ubuntu-190][website]].

There is a button in the header of that page where you select the version of
Debian/Ubuntu distribution.

Typically for Ubuntu 20.04 those are the steps:

#!BEGIN_SRC
    $ wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    $ sudo dpkg -i packages-microsoft-prod.deb
    $ sudo apt-get update
    $ sudo apt-get install apt-transport-https
    $ sudo apt-get update
    $ sudo apt install dotnet-runtime-3.1 dotnet-sdk-3.1 dotnet-hostfxr-3.1
#!END_SRC

* [BROKEN] Installing PL/.NET in Linux - Ubuntu/Debian flavours

Installing PostgreSQL:

#+BEGIN_SRC
    $ sudo apt install postgresql postgresql-common
#+END_SRC

Download the `pldotnet` binary package available for your Postgres version:
- [[https://brickabode.com/pldtonet/postgres-10-pldotnet_0.1-1_amd64.deb][postgres-10-pldotnet_0.1-1_amd64]]
- [[https://brickabode.com/pldtonet/postgres-11-pldotnet_0.1-1_amd64.deb][postgres-11-pldotnet_0.1-1_amd64]]
- [[https://brickabode.com/pldtonet/postgres-12-pldotnet_0.1-1_amd64.deb][postgres-12-pldotnet_0.1-1_amd64]]
- [[https://brickabode.com/pldtonet/postgres-13-pldotnet_0.1-1_amd64.deb][postgres-13-pldotnet_0.1-1_amd64]]

And install it:
#+BEGIN_SRC
    $ sudo dpkg -i postgres-*-pldotnet_0.1-1_amd64.deb
#+END_SRC

* Installing PL/.NET on other OSes

Currently we are developing for Linux Ubuntu 20.04 LTS however
we plan to support all OSes are also supported by Postgres and .NET and you
have an option to experiment PL/.NET: Docker.

We constantly use Docker in our development computers then you also
can benefit of it case your OS is not the supported one:
Run the following commands to start a ready-for-use container:

#+BEGIN_SRC
$ git clone https://github.com/brickabode/pldotnet.git
$ cd pldotnet
$ docker-compose run pldotnet-<OS_distro> bash
$ runuser -u postgres -- psql -c "CREATE EXTENSION pldotnet;"
#+END_SRC

Make sure to replace `<OS_distro>` by one of the supported distributions:
- `deb`
- `ubuntu18`
- `ubuntu20`
- `ubuntu21`
- `devenv` this is an alias for the lastest LTS supported Ubuntu version (20.04)

* Building Debian/Ubuntu package

We're also using Docker to build our deb packages. You can build them by
running the following commands:

#+BEGIN_SRC
    $ git clone https://github.com/brickabode/pldotnet.git
    $ cd pldotnet
    $ docker-compose -f docker-compose-build.yml up pldotnet-build
#+END_SRC

The packages will be stored in `pldotnet/debian/packages/` directory.

Once the packages are built you can remove the container with:
#+BEGIN_SRC
    $ docker-compose -f docker-compose-build.yml down
#+END_SRC

